prefab-cloud/prefab-cloud-docs-web

docs/ruby-sdk/ruby.md

Small tweaks to better reflect reality

Cleanup ruby docs

---

docs/java-sdk/java-logging.md
docs/java-sdk/java.md

Includes breaking out the separate logging dependencies

Update docs for new 0.3.2 java client release

---

docs/elixir-sdk/_category_.json
docs/python-sdk/_category_.json
docs/python-sdk/dynamic_log_levels.md
docs/python-sdk/python.md
docs/ruby-sdk/dynamic-log-levels.md
docusaurus.config.js
package.json
yarn.lock

* Add overview of Python client
* Add Python section on dynamic log levels
Also
* Correct some prism highlighting keys in the Elixir docs

Add Python documentation

---

docs/elixir-sdk/elixir.md
docs/explanations/bootstrapping.md
docs/explanations/client-sdks.md
docs/explanations/core.md
docs/explanations/namespaces.md
docs/explanations/resiliency.md
docs/explanations/rules-and-segmentation.md
docs/explanations/testing.md
docs/how-tos/beta-releases.md
docs/how-tos/tracking-ids.md
docs/python-sdk/python.md
docs/tutorials/get-started.md
src/components/HomepageFeatures/index.js

- move tracking id advice to how-tos and move the Rails bit under a
Rails tab
- More tabs to come later, presumably
- lots of whitespace cleanup
- remove defunct rules
- change some Prefab.Cloud instances to Prefab

Misc tweaks

---

docs/explanations/server-sdks.md
docusaurus.config.js
package.json
yarn.lock

Also includes some basic theme overrides and a new diagram for the Server SDK explanation page.

Adds Mermaid diagram support

---

docs/elixir-sdk/elixir.md
docs/explanations/client-sdks.md
docs/explanations/resiliency.md
docs/explanations/server-sdks.md
docs/python-sdk/python.md
docs/ruby-sdk/ruby.md
package.json
yarn.lock

Server SDK diagram
Client SDK diagram

Updating docs for accuracy and clarity

---

src/pages/index.js
src/theme/Footer/index.js

respect the tid cookie or set.

set our tid

---

docs/python-sdk/python.md

Update the Python client docs to remove documentation for lookup_key/properties/attributes and instead point to the shared docs on context and provide python code samples

Replace lookup_key/properties docs with context docs

---

docs/elixir-sdk/elixir.md
docs/python-sdk/python.md

Seems to be auto generated from the first heading

Fix meta descriptions for some pages

---

docs/node-sdk/node.md

This has been used successfully in prod now.

Remove node disclaimer

---

docs/node-sdk/node.md
src/pages/index.js

- Update node docs
- Add node to language index and re-order languages

Node Docs + Add to Index

---

docs/elixir-sdk/elixir.md
docs/explanations/bootstrapping.md
docs/explanations/client-sdks.md
docs/explanations/context.md
docs/explanations/defaults.md
docs/explanations/namespaces.md
docs/explanations/testing.md
docs/how-tos/beta-releases.md
docs/how-tos/tracking-ids.md
docs/javascript.md
docs/python-sdk/python.md
docs/react.md
docs/ruby-sdk/ruby.md
docs/tutorials/get-started.md
src/theme/MDXComponents.js

No longer necessary to import Tabs and TabItem into each page

Global import of tabs component

---

docs/explanations/concepts/context.md
docs/explanations/concepts/testing.md

datafile wip

---

docs/sdks/node.md

You don't have to use a Map here anymore

Update node context

---

docs/sdks/elixir.md
docs/sdks/java.md
docs/sdks/javascript.md
docs/sdks/node/netlify.md
docs/sdks/node/node.md
docs/sdks/python.md
docs/sdks/react-native.md
docs/sdks/react.md
docs/sdks/ruby.md

Netlify docs are re-purposed from blog posts

Docs for Netlify and reorganize SDK docs

---

docs/sdks/node/node.md

The netlify content was confusing here

Fix shouldLog signature for node and update docs for clarity

---

docs/sdks/python.md

python docs improvements

---

docs/sdks/go.md
docs/sdks/ruby.md

Add Ruby SDK JS stub/bootstrap info

---

yarn.lock

This should address some vulnerabilities.

Upgrades all packages

---

docs/explanations/concepts/zero-ms-frontend-feature-flags.md
docs/sdks/ruby.md

We don't want this html-escaped

Double equals, not single
